spring:
  application:
    name: core-product
  webflux:
    base-path: /core-product/v1
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mypostgresdb
    username: postgresuser
    password: postgrespassword
  sql:
    init:
      mode: always
      schema-locations: classpath:/data.sql
      continue-on-error: true
  jpa:
    defer-datasource-initialization: true
  data:
    mongodb:
      uri: mongodb://mongoadmin:mongopassword@localhost:27017/product-directory?authSource=admin
  main:
    allow-bean-definition-overriding: true
server:
  port: 80
springdoc:
  api-docs:
    enabled: true
    path: /openapi
  show-actuator: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,openapi,swagger-ui,mappings
openapi:
  coreProduct:
    base-path:
logging:
  level:
    org.springframework: DEBUG
    com.lapositiva.services.productdirectory: DEBUG
resilience4j.circuitbreaker:
  instances:
    product:
      registerHealthIndicator: true
      slidingWindowSize: 100
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - com.example.MyException
      ignoreExceptions:
        - java.lang.IllegalStateException

resilience4j.retry:
  instances:
    product:
      maxRetryAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      maxWaitDuration: 10s
      retryExceptions:
        - com.example.MyException
      ignoreExceptions:
        - java.lang.IllegalStateException
application:
  api:
    error-code.invalid-request.error-type: Functional
    error-code.invalid-request.description: Bad Request
    error-code.invalid-request.code: 400
    error-code.resource-not-found.error-type: Functional
    error-code.resource-not-found.description: Not found
    error-code.resource-not-found.code: 404
    error-code.conflict.error-type: Functional
    error-code.conflict.description: Conflict
    error-code.conflict.code: 409
    error-code.external-error.error-type: Technical
    error-code.external-error.description: Internal server error
    error-code.external-error.code: 500
    error-code.host-not-found.error-type: Technical
    error-code.host-not-found.description: Internal server error
    error-code.host-not-found.code: 500
    error-code.unexpected.error-type: Technical
    error-code.unexpected.description: Internal server error
    error-code.unexpected.code: 500
    error-code.not-implemented.error-type: Technical
    error-code.not-implemented.description: Not Implemented
    error-code.not-implemented.code: 501
    error-code.service-unavailable.error-type: Technical
    error-code.service-unavailable.description: Service unavailable (Circuit Breaker)
    error-code.service-unavailable.code: 503
    error-code.external-timeout.error-type: Technical
    error-code.external-timeout.description: Service unavailable
    error-code.external-timeout.code: 503
